// Builds the headline face for the Chinese homepage: Noto Serif SC Black cut down to the
// characters the display copy actually uses (~30 KB instead of ~370 KB of unicode-range slices).
//
//   node scripts/display-font.mjs <path/to/NotoSerifSC-Black.otf>   rebuild the subset + its CSS
//   node scripts/display-font.mjs --check                            fail if a headline has a character the subset lacks
//
// Source font: https://raw.githubusercontent.com/notofonts/noto-cjk/main/Serif/SubsetOTF/SC/NotoSerifSC-Black.otf
// (SIL OFL 1.1, license text in public/fonts/OFL-noto-serif-sc.txt). Needs Python fontTools + brotli.
//
// Re-run after editing any string listed in DISPLAY below; CI runs --check. A character missing from
// the subset still renders, but in the system serif (Songti SC on macOS), so the headline mixes faces.
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync, rmSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { COPY } from "../src/i18n/bioseeki.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const cssPath = join(root, "src/styles/display-font.css");
const fontPath = join(root, "public/fonts/noto-serif-sc-900-display.woff2");

// Every zh string Home.astro sets in the display face.
const zh = COPY.zh;
const DISPLAY = [
  zh.hero.h1a, zh.hero.h1b,
  zh.tools.title, zh.tools.gc.h, zh.verify.title, zh.principles.title, zh.workflow.title,
  zh.demo.title, zh.download.title, zh.pricing.title, zh.faq.title,
  zh.footer.tagA, zh.footer.tagB,
];
const ASCII = Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i)).join("");
const PUNCT = "，。、：；？！「」『』（）《》〈〉—…·“”‘’¥";
const needed = [...new Set([...DISPLAY.join("")])].filter((c) => c.trim());

if (process.argv[2] === "--check") {
  const range = /unicode-range:([^;]+);/.exec(readFileSync(cssPath, "utf8"))[1];
  const spans = range.split(",").map((r) => r.trim().replace("U+", "").split("-").map((h) => parseInt(h, 16)));
  const covered = (cp) => spans.some(([a, b = a]) => cp >= a && cp <= b);
  const missing = needed.filter((c) => !covered(c.codePointAt(0)));
  if (missing.length) {
    console.error(`display font lacks ${missing.length} character(s) used in headlines: ${missing.join("")}`);
    console.error("rebuild it: node scripts/display-font.mjs <NotoSerifSC-Black.otf>  (see the header of this script)");
    process.exit(1);
  }
  console.log(`display font covers all ${needed.length} headline characters`);
  process.exit(0);
}

const src = process.argv[2];
if (!src) { console.error("usage: node scripts/display-font.mjs <NotoSerifSC-Black.otf> | --check"); process.exit(1); }
const chars = [...new Set([...needed, ...ASCII, ...PUNCT])].sort();

const tmp = mkdtempSync(join(tmpdir(), "display-font-"));
const textFile = join(tmp, "chars.txt");
writeFileSync(textFile, chars.join(""));
execFileSync("python3", [
  "-m", "fontTools.subset", src, `--text-file=${textFile}`, `--output-file=${fontPath}`, "--flavor=woff2",
  "--layout-features+=palt", "--desubroutinize", "--no-hinting",
], { stdio: "inherit" });
rmSync(tmp, { recursive: true, force: true });

// unicode-range lets the browser skip this file for any character it does not hold.
const cps = chars.map((c) => c.codePointAt(0)).sort((a, b) => a - b);
const ranges = [];
for (const cp of cps) {
  const last = ranges[ranges.length - 1];
  if (last && cp === last[1] + 1) last[1] = cp; else ranges.push([cp, cp]);
}
const hex = (n) => n.toString(16).toUpperCase();
const range = ranges.map(([a, b]) => (a === b ? `U+${hex(a)}` : `U+${hex(a)}-${hex(b)}`)).join(",");
writeFileSync(cssPath, `/* Generated by scripts/display-font.mjs — do not edit by hand.
   Noto Serif SC Black (SIL OFL 1.1, public/fonts/OFL-noto-serif-sc.txt), cut to the ${chars.length} characters
   of the homepage display copy plus ASCII and CJK punctuation. */
@font-face{
  font-family:"BioSeeki Display";
  font-style:normal;
  font-weight:900;
  font-display:swap;
  src:url("/fonts/noto-serif-sc-900-display.woff2") format("woff2");
  unicode-range:${range};
}
`);
console.log(`${chars.length} chars -> ${fontPath} (${Math.round(statSync(fontPath).size / 1024)} KB)`);
