// Regenerates src/components/bioseeki/icons.ts from Phosphor Icons (MIT).
// Only the icons the homepage uses are vendored, so the site does not carry the whole package.
//
//   npm i --no-save @phosphor-icons/core@2.1.1 && node scripts/gen-icons.mjs
//   (or, with the package installed elsewhere: NODE_PATH=<dir>/node_modules node scripts/gen-icons.mjs)
//
// To swap an icon, change its name below and rerun; browse https://phosphoricons.com for names.
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
// the package does not export ./package.json, so walk up from its main entry
let pkgDir = path.dirname(require.resolve("@phosphor-icons/core"));
while (!fs.existsSync(path.join(pkgDir, "assets"))) pkgDir = path.dirname(pkgDir);
const { version } = JSON.parse(fs.readFileSync(path.join(pkgDir, "package.json"), "utf8"));

// sprite id → [phosphor name, weight]. Feature icons use "regular"; glyphs that sit inside
// running text use "bold" so they keep the weight of the letters around them.
const ICONS = {
  // capabilities
  "i-search": ["binoculars", "regular"],
  "i-chart": ["chart-scatter", "regular"],
  "i-doc": ["pen-nib", "regular"],
  "i-figure": ["squares-four", "regular"],
  // verifiable
  "i-quote": ["quotes", "regular"],
  "i-shield": ["seal-check", "regular"],
  "i-redo": ["arrows-counter-clockwise", "regular"],
  "i-gap": ["selection", "regular"],
  // knowledge & memory
  "i-book": ["book-open-text", "regular"],
  "i-lang": ["translate", "regular"],
  "i-memory": ["stack", "regular"],
  // boundaries
  "i-hand": ["hand-palm", "regular"],
  "i-lock": ["folder-lock", "regular"],
  "i-globe": ["globe-simple", "regular"],
  "i-nodata": ["eye-slash", "regular"],
  // account menu, FAQ, video
  "i-user": ["user", "regular"],
  "i-signout": ["sign-out", "regular"],
  "i-caret": ["caret-down", "bold"],
  "i-plus": ["plus", "regular"],
  "i-play": ["play", "fill"],
  // glyphs drawn in place of ↗ ↓ ↑ → ✉ ✓ ✗ ! ? in the copy (see glyphs.ts)
  "a-ext": ["arrow-up-right", "bold"],
  "a-down": ["arrow-down", "bold"],
  "a-up": ["arrow-up", "bold"],
  "a-right": ["arrow-right", "bold"],
  "a-mail": ["envelope-simple", "bold"],
  "g-check": ["check", "bold"],
  "g-x": ["x", "bold"],
  "g-alert": ["exclamation-mark", "bold"],
  "g-q": ["question-mark", "bold"],
};

const body = (name, weight) => {
  const file = path.join(pkgDir, "assets", weight, weight === "regular" ? `${name}.svg` : `${name}-${weight}.svg`);
  const svg = fs.readFileSync(file, "utf8");
  // keep the drawing, drop the 256×256 wrapper; paths are filled with currentColor
  return svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").replace(/\s*fill="currentColor"/g, "").trim();
};

const lines = Object.entries(ICONS).map(([id, [name, weight]]) => `  ${JSON.stringify(id)}: ${JSON.stringify(body(name, weight))}, // ${name} (${weight})`);
const out = `// Generated by scripts/gen-icons.mjs from Phosphor Icons ${version} — do not edit by hand.
// Phosphor Icons © 2023 Phosphor Icons, MIT License (full text in ./icons.LICENSE).
// Every entry is the inside of a 256×256 SVG; Home.astro wraps each one in a <symbol>.
export const ICON_VIEWBOX = "0 0 256 256";
export const ICONS: Record<string, string> = {
${lines.join("\n")}
};
`;
const target = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../src/components/bioseeki/icons.ts");
fs.writeFileSync(target, out);
fs.copyFileSync(path.join(pkgDir, "LICENSE"), target.replace(/icons\.ts$/, "icons.LICENSE"));
console.log(`wrote ${Object.keys(ICONS).length} icons → ${path.relative(process.cwd(), target)}`);
